force-app/main/default/objects/Webinar__c/Webinar__c.object-meta.xml
<CustomObject>
    <description>Public webinars for lead-generation</description>
    <label>Webinar</label>
    <nameField>
        <label>Webinar Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Webinars</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Webinar__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <description>Description or agenda of the webinar</description>
    <label>Description</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Webinar__c/fields/Duration__c.field-meta.xml
<CustomField>
    <fullName>Duration__c</fullName>
    <description>Duration of the webinar in minutes</description>
    <label>Duration (Minutes)</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Webinar__c/fields/Link__c.field-meta.xml
<CustomField>
    <fullName>Link__c</fullName>
    <description>Public link to join the webinar, sent in a confirmation email after the registrant fills out the registration form</description>
    <label>Link</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Webinar__c/fields/StartTime__c.field-meta.xml
<CustomField>
    <fullName>StartTime__c</fullName>
    <description>Datetime for the start of the webinar</description>
    <label>Start Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/WebinarRegistrant__c/WebinarRegistrant__c.object-meta.xml
<CustomObject>
    <description>Tracks the registrants for a webinar</description>
    <label>Webinar Registrant</label>
    <nameField>
        <displayFormat>REG-{00000}</displayFormat>
        <label>Webinar  Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Webinar Registrants</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/WebinarRegistrant__c/fields/Lead__c.field-meta.xml
<CustomField>
    <fullName>Lead__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The lead who is registering for the webinar</description>
    <label>Lead</label>
    <referenceTo>Lead</referenceTo>
    <relationshipLabel>Webinars</relationshipLabel>
    <relationshipName>WebinarRegistrants</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/WebinarRegistrant__c/fields/Webinar__c.field-meta.xml
<CustomField>
    <fullName>Webinar__c</fullName>
    <description>The webinar that a lead is registering for</description>
    <label>Webinar</label>
    <referenceTo>Webinar__c</referenceTo>
    <relationshipLabel>Registrants</relationshipLabel>
    <relationshipName>WebinarRegistrants</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/WebinarHandler.cls
public without sharing class WebinarHandler {

     /**
     * Checks for existing campaign membership for a lead, and then
     * if none, will create a CampaignMember
     */
    public static void createCampaignMember(Id campaignId, Id leadId) {
        CampaignMember[] existingCampaignMember = [
            SELECT Id FROM CampaignMember WHERE CampaignId = :campaignId AND LeadId = :leadId
        ];
        
        if (existingCampaignMember.isEmpty()) {
            insert new CampaignMember(
                CampaignId = campaignId,
                LeadId = leadId
            );
        }
    }

    public static void createWebinarRegistrant(Id webinarId, Id leadId) {
        insert new WebinarRegistrant__c(
            Webinar__c = webinarId,
            Lead__c = leadId
        );
    }

    public static void sendInvitationEmail(Webinar__c webinar, Lead lead) {
        Messaging.SingleEmailMessage msg = new Messaging.SingleEmailMessage();
        List<Messaging.EmailFileAttachment> attachments = new List<Messaging.EmailFileAttachment>();
        attachments.add(createCalendarAttachment(webinar));
        msg.setFileAttachments(attachments);
        msg.setSubject('Your invitation for: ' + webinar.Name);
        msg.setPlainTextBody('Hi ' + lead.FirstName + ',\n' +
                            'Join our webinar at... (TODO)');
        List<String> toAddresses = new List<String>{lead.Email};
        msg.setToAddresses(toAddresses);
        List<Messaging.SingleEmailMessage> msgsToSend = new List<Messaging.SingleEmailMessage>{msg};
        Messaging.sendEmail(msgsToSend);
    }

    public static Messaging.EmailFileAttachment createCalendarAttachment(Webinar__c webinar) {
        DateTime startTime = webinar.StartTime__c;
        DateTime endTime = webinar.StartTime__c.addMinutes((Integer)webinar.Duration__c);
        String dateFormat = 'yyyyMMdd\'T\'HHmmss\'Z\'';

        String icsString =  'BEGIN:VCALENDAR\r\n' +
                            'VERSION:2.0\r\n' +
                            'PRODID:-//ZContent.net//Zap Calendar 1.0//EN\r\n' +
                            'CALSCALE:GREGORIAN\r\n' +
                            'METHOD:PUBLISH\r\n' +
                            'BEGIN:VEVENT\r\n' +
                            'SUMMARY:' + webinar.Name + '\r\n' +
                            'UID:' + webinar.Id + '\r\n' +
                            'SEQUENCE:0\r\n' +
                            'DTSTAMP:' + startTime.formatGMT(dateFormat) + '\r\n' +
                            'DTSTART:' + startTime.formatGMT(dateFormat) + '\r\n' +
                            'DTEND:' + endTime.formatGMT(dateFormat) + '\r\n' +
                            'DESCRIPTION:' + formatCalendarDescription(webinar) + '\r\n' +
                            'URL:' + webinar.Link__c + '\r\n' +
                            'END:VEVENT\r\n' +
                            'END:VCALENDAR\r\n';
        
        Messaging.EmailFileAttachment attch = new Messaging.EmailFileAttachment();
        attch.body = Blob.valueOf(icsString);
        attch.filename = 'invite.ics';
        attch.contenttype = 'text/calendar';
        return attch;
    }

    private static String formatCalendarDescription(Webinar__c webinar) {
        String description = webinar.Description__c.replace('\n', '\\n');
        description += '\\n\\n Join link: ' + webinar.Link__c;
        return description;
    }
}