force-app/main/default/objects/Webinar__c/Webinar__c.object-meta.xml
<CustomObject>
    <description>Public webinars for lead-generation</description>
    <label>Webinar</label>
    <nameField>
        <label>Webinar Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Webinars</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Webinar__c/fields/Campaign__c.field-meta.xml
<CustomField>
    <fullName>Campaign__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Related sales-campaign for the webinar</description>
    <label>Campaign</label>
    <referenceTo>Campaign</referenceTo>
    <relationshipLabel>Webinars</relationshipLabel>
    <relationshipName>Webinars</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Webinar__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <description>Description or agenda of the webinar</description>
    <label>Description</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Webinar__c/fields/Duration__c.field-meta.xml
<CustomField>
    <fullName>Duration__c</fullName>
    <description>Duration of the webinar in minutes</description>
    <label>Duration (Minutes)</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Webinar__c/fields/IsPublic__c.field-meta.xml
<CustomField>
    <fullName>IsPublic__c</fullName>
    <defaultValue>false</defaultValue>
    <description>When checked, this field becomes available on the public community page</description>
    <label>Is Public</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Webinar__c/fields/Link__c.field-meta.xml
<CustomField>
    <fullName>Link__c</fullName>
    <description>Public link to join the webinar, sent in a confirmation email after the registrant fills out the registration form</description>
    <label>Link</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Webinar__c/fields/StartTime__c.field-meta.xml
<CustomField>
    <fullName>StartTime__c</fullName>
    <description>Datetime for the start of the webinar</description>
    <label>Start Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Webinar__c/fields/Topics__c.field-meta.xml
<CustomField>
    <fullName>Topics__c</fullName>
    <label>Topics</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Rudiments</fullName>
            </value>
            <value>
                <fullName>Musicianship</fullName>
            </value>
            <value>
                <fullName>Product Review</fullName>
            </value>
            <value>
                <fullName>Live Demo</fullName>
            </value>
            <value>
                <fullName>Q&amp;A</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/TestDataFactory.cls
@IsTest
public with sharing class TestDataFactory {

    /**
     * Creates test campaigns and one webinar per topic for each
     */
    public static void createWebinarsWithCampaigns(Integer numCampaigns) {
        List<Campaign> campaigns = new List<Campaign>();
        for (Integer i=0; i< numCampaigns; i++) {
            campaigns.add(new Campaign(Name = 'Test Campaign ' + i));
        }
        insert campaigns;

        List<Webinar__c> webinars = new List<Webinar__c>();
        for (Campaign cmp : campaigns) {
            for (String topic : Consts.getWebinarTopics()) {
                webinars.add(new Webinar__c(
                    Name = topic,
                    Topics__c = topic,
                    IsPublic__c = true,
                    Description__c = 'Test webinar for ' + topic,
                    Campaign__c = cmp.Id,
                    StartTime__c = System.now().addDays(1),
                    Duration__c = 30,
                    Link__c = 'https://google.com'
                ));
            }
        }

        insert webinars;
    }
}